[package]
name = "import-derive"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0"
quote = "1"
proc-macro2 = "1.0"
syn = { version = "2.0", default-features = true, features = ["extra-traits", "full"] }
case = "1.0.0"
