[package]
name = "huckli-db"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
async-duckdb.workspace = true
duckdb.workspace = true
futures.workspace = true
itertools.workspace = true
thiserror.workspace = true
tokio.workspace = true
