name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build
      cancel-in-progress: true
    container:
      image: ubuntu:20.04
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}-fmt
      cancel-in-progress: true
    steps:
      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          # apt-get install -y tzdata curl build-essential pkg-config libssl-dev clang lld cmake unzip
          apt-get install -y curl build-essential protobuf-compiler
          # ln -fs /usr/share/zoneinfo/UTC /etc/localtime
          # dpkg-reconfigure -f noninteractive tzdata

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup | Rust toolchain
        uses: dtolnay/rust-toolchain@1.85.0

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}


      - name: build
        run: cargo build

